# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:

  adapter: postgresql

  encoding: unicode

  database: pgdatabase

  pool: 5

  username: postgres

  password: theAlchemist

 

test:

  adapter: postgresql

  encoding: unicode

  database: pgdatabase

  pool: 5

  username: postgres

  password: theAlchemist

 

production:

  adapter: postgresql

  encoding: unicode

  database: pgdatabase

  pool: 5

  username: postgres

  password: theAlchemist